
name: Send Contact Email

on:
    repository_dispatch:
        types: [send_email]

jobs:
    send-email:
        runs-on: ubuntu-latest

        steps:
              - name: Send Email to User
                uses: dawidd6/action-send-mail@v3
                with:
                    server_address: "smtp.gmail.com"
                    server_port: "465"
                    secure: true
                    username: "amandange7676@gmail.com"
                    password: "dock bpmc qeqk zyhd"
                    subject: ${{ github.event.client_payload.subject }}
                    to: "amandange7676@gmail.com"
                    from: ${{ github.event.client_payload.from_email }}
                    body: |
                        ${{ github.event.client_payload.body }}

              - name: Send Email to Admin
                uses: dawidd6/action-send-mail@v3
                with:
                    server_address: "smtp.gmail.com"
                    server_port: "465"
                    secure: true
                    username: "amandange7676@gmail.com"
                    password: "dock bpmc qeqk zyhd"
                    subject: ${{ github.event.client_payload.subject }}
                    to: fashionsense482@gmail.com
                    from: "amandange7676@gmail.com"
                    body: |
                        ${{ github.event.client_payload.from_email }}
                        Message:
                        ${{ github.event.client_payload.body }}
                